#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>
void textcolor(int color_number)
{
      SetConsoleTextAttribute( GetStdHandle( STD_OUTPUT_HANDLE ), color_number);
};

float absolute(float a)
{
	if(a<0) return -a;
	return a;
}
void swap(int *a, int *b){
	int tmp = *a;
	*a = *b;
	*b = tmp;
}
int gnd(int a, int b){
	int tmp;
	if(a==b) return a;
	if(a<b) swap(&a,&b);
	while(b){
		tmp = a;
		a = b;
		b = tmp%b;
	}
	return a;
}
float squareRoot(int a)
{
	float guess=1.0;
	const float eps = 0.00001;
	while(absolute(guess * guess - a) >= eps)
	 guess=(a/guess+guess) / 2.0;
	 return guess;
}
void firstequator(int a,int b){
    float solve;
	printf("일차방정식 = 0의 계수를 각각 입력해주세요\n");
	printf("ax + b = 0의 꼴로 정리해 정수 a,b를 차례대로 입력하세요(예시:1 -2)\n");
	scanf("%d %d",&a,&b);
	solve = (float)b/a;
	solve = -solve;
	printf("1차방정식의 해는 %f\n",solve);
}
void secequator(int a,int b, int c){
    float solve1,solve2; 
	printf("이차방정식 = 0의 계수를 각각 입력해 주세요\n");
	printf("ax^2 + bx + c = 0의 꼴로 정리해 정수 a,b,c를 차례대로 입력하세요(예시:1 2 1)\n"); 
	scanf("%d %d %d",&a,&b,&c);
	if(b*b - 4*a*c>0){
	solve1 = (-b+squareRoot(b*b - 4*a*c)) / (a*2);
	solve2 = (-b-squareRoot(b*b - 4*a*c)) / (a*2);
	printf("이차방정식의 두 실근은 %f %f\n",solve1,solve2);
    }
    else if(b*b - 4*a*c==0){
      	solve1 = (-b / (a*2));
      	printf("이차방정식의 중근은 %f\n",solve1);
	}
	else{
	    solve1 = (-b+squareRoot(absolute(b*b - 4*a*c))) / (a*2);
	    solve2 = (-b-squareRoot(absolute(b*b - 4*a*c))) / (a*2);
	    printf("이차방정식의 두 허근은 %fi %fi\n",solve1,solve2);
	}
}
int Nsquare(int a){
	int n;
	int solve=1;
	printf("%d를 몇번 제곱할지 입력하세요.\n",a);
	scanf("%d",&n);
	for(int i=0; i<n; i++) solve = solve*a;
	printf("%d의 제곱근은 %d\n",a,solve);
}

int main(void)
{
	int tmp;
    int a,b,c;
    char d;
    textcolor(11);
    int dly=80;
     printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍                                                               =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고                                                         =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등                                                      =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학                                                   =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1                                                       =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학                                                    =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년                                                 =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반                                             =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이                                        =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하                                     =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계                                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산                                               =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프                                         =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프 로                                      =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프 로 그                                   =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프 로 그 램                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly+100);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly+100);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프 로 그 램                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly+100);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly+100);
	 system("cls");
	 printf("==============================================================================\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=           홍 성 고 등 학 교                                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                    1 학년 2 반   이 하 동                                  =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                        계 산 기 프 로 그 램                                =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("=                                                                            =\n");
	 printf("==============================================================================\n");
	 Sleep( dly); // 인트로 종료  
	 textcolor(15);
    label1:
    printf("사칙연산은 1을, 방정식은 2를 눌러주세요.\n");
    scanf("%d",&tmp);
    if(tmp==1){
	printf("두 정수를 입력해주세요.\n예시)10 20\n");
	scanf("%d %d",&a,&b);
	label4:
	printf("더하기: +\n빼기: -\n나누기: /\n곱하기: *\n최대공약수:G\n최소공배수: M\n제곱근: R\nN제곱: N\n");
	scanf(" %c",&d);
    switch(d){
    	case '+': printf("%d + %d = %d\n",a,b,a+b);
    	break;
    	case '-': printf("%d - %d = %d\n",a,b,a-b);
    	break;
		case '*': printf("%d X %d = %d\n",a,b,a*b);
    	break;
		case '/': printf("%d / %d = %f\n",a,b,(float) a/b);
    	break;
		case 'G': printf("%d와 %d의 최대공약수는 %d\n",a,b,gnd(a,b));
    	break;
    	case 'M': printf("%d와 %d의 최소공배수는 %d\n",a,b,a*b/gnd(a,b));
    	break;
		case 'R': if(a>=0) printf("%d의 제곱근은 %f\n",a,squareRoot(a));
		          else{
		          	printf("%d의 제곱근은 %fi\n",a,squareRoot(-a));
				  }
				  if(b>=0) printf("%d의 제곱근은 %f\n",b,squareRoot(b));
		          else{
		          	printf("%d의 제곱근은 %fi\n",b,squareRoot(-b));
				  }
    	break;
		case 'N': Nsquare(a); Nsquare(b); printf("\n");
		break;
		default: printf("잘못된 입력입니다.\n"); goto label4; 
	}
	printf("처음으로 돌아가시려면 1을, 종료하시려면 0을 눌러주세요.\n");
	scanf("%d",&tmp);
	if(tmp==1) goto label1;
	else if(tmp==0) return 0;
	else{
		printf("잘못된 입력입니다.\n");
		goto label2;
	}
	}
	else if(tmp==2){
		label3:
		printf("1차방정식은 1을, 2차방정식은 2를 눌러주세요\n");
		scanf("%d",&tmp);
		if(tmp==1){
		 firstequator(a,b);
	    }
	    else if(tmp==2){
	    	secequator(a,b,c);
		}
		else{
			printf("잘못된 입력입니다.\n");
			goto label3;
		}
	label2:
	printf("처음으로 돌아가시려면 1을, 종료하시려면 0을 눌러주세요.\n");
	scanf("%d",&tmp);
	if(tmp==1) goto label1;
	else if(tmp==0) return 0;
	else{
		printf("잘못된 입력입니다.\n");
		goto label2;
	}
}
    else{
	   printf("잘못된 입력입니다.\n");
	   goto label1;;	
	} 
}
